---
title: "Untitled"
output: html_document
date: "2022-07-20"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(dplyr.summarise.inform = FALSE)
options(scipen = 999)

library(tidyverse)
library(knitr)
library(scales)
library(kableExtra)
library(readxl)
# source("R/eda.R")
```

## Intro

## Translate Variables

```{r}
per <- read_csv("data/_private/hh_survey/input/person.csv")
hh <- read_csv("data/_private/hh_survey/input/hh.csv")
loc <- read_csv("data/_private/hh_survey/input/location.csv")
trip <- read_csv("data/_private/hh_survey/input/linked_trip.csv")
```

```{r}
translate_table <- function(tbl){
  equiv_tbl <- read_csv("data/_private/hh_survey/input/equiv_table.csv")
  
  variables <- unique(equiv_tbl$VARIABLE)
  col_names <- colnames(tbl)
  for (variable in variables) {
    if (!(variable %in% col_names)) next
    
    tmp <- equiv_tbl %>%
      filter(VARIABLE == variable) %>%
      select(CODE, EQUIV)

    tbl <- tbl %>%
      rename(temp = variable) %>%
      left_join(tmp, by = c("temp" = "CODE")) %>%
      mutate(temp = ifelse(is.na(EQUIV), temp, EQUIV)) %>%
      select(-EQUIV) %>%
      rename(!!variable := temp)
  }
  return(tbl)
}
```

```{r}
translate_hh <- translate_table(hh)
translate_per <- translate_table(per)
translate_loc <- translate_table(loc)
translate_trip <- translate_table(trip)
```

# Geocoding

```{r, include=FALSE}
hh_pts <- hh %>%
  mutate(unique_id = paste(home_lon, home_lat, sep = "_")) %>%
  select(unique_id, longitude = home_lon, latitude = home_lat)
per_pts <- bind_rows(
  per %>%
    mutate(unique_id = paste(work_lon, work_lat, sep = "_")) %>%
    select(unique_id, longitude = work_lon, latitude = work_lat),
  per %>%
    mutate(unique_id = paste(school_lon, school_lat, sep = "_")) %>%
    select(unique_id, longitude = school_lon, latitude = school_lat)
)
# the loc file has GPS trace points, so don't include those
trip_pts <- bind_rows(
  trip %>%
    mutate(unique_id = paste(o_lon, o_lat, sep = "_")) %>%
    select(unique_id, longitude = o_lon, latitude = o_lat),
  trip %>%
    mutate(unique_id = paste(d_lon, d_lat, sep = "_")) %>%
    select(unique_id, longitude = d_lon, latitude = d_lat)
)

# Use this table in TransCAD to geocode points to TAZs then read back in
to_geocode <- bind_rows(hh_pts, per_pts, trip_pts) %>%
  group_by(unique_id) %>%
  slice(1) %>%
  filter(!is.na(longitude) & longitude != -1)
write_csv(to_geocode, "data/_private/hh_survey/output/to_geocode.csv")
geocoded_pts <- read_csv("data/_private/hh_survey/output/geocoded_points.csv") %>%
  select(unique_id, TAZ)

hh_with_tazs <- translate_hh %>%
  mutate(unique_id = paste(home_lon, home_lat, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(HomeTAZ = TAZ) %>%
  select(-unique_id)

per_with_taz <- translate_per %>%
  mutate(unique_id = paste(work_lon, work_lat, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(WorkTAZ = TAZ) %>%
  mutate(unique_id = paste(school_lon, school_lat, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(SchoolTAZ = TAZ) %>%
  select(-unique_id)

trip_with_taz <- translate_trip %>%
  mutate(unique_id = paste(o_lon, o_lat, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(o_taz = TAZ) %>%
  mutate(unique_id = paste(d_lon, d_lat, sep = "_")) %>%
  left_join(geocoded_pts, by = "unique_id") %>%
  rename(d_taz = TAZ) %>%
  select(-unique_id)
```

## Calculate HHStructure

```{r}
per_calc_ptypes <- per_with_taz %>%
  mutate(
    WAdult = ifelse(employment %in% c("full", "part", "self") & age >= 18, 1, 0),
    NWAdult = ifelse(WAdult == 0 & age >= 18, 1, 0),
    Kid = ifelse(age %in% c("Under 5", "5 to 15", "16 to 17"), 1, 0),
    PreSch = ifelse(age == "Under 5", 1, 0),
    Senior = ifelse(age %in% c("65 to 74", "75 to 84"), 1, 0),
    Licensed_Driver = ifelse(can_drive == "yes", 1, 0)
  )

hhstructure <- per_calc_ptypes %>%
  group_by(hh_id) %>%
  summarise(
    WAdults = sum(WAdult), NWAdults = sum(NWAdult), HHKids = sum(Kid), 
    HHPreSchs = sum(PreSch), HHSeniors = sum(Senior),
    HHDrvLic = sum(Licensed_Driver)
  ) %>%
  mutate(HHStructure = paste0("HH_", WAdults, NWAdults, HHKids))

hh_add_strct <- hh_with_tazs %>%
  left_join(hhstructure, by = "hh_id")
  
```

## Convert modes to model modes

```{r}
convert_modes <- loc_with_taz %>%
  mutate(
    mode_model = case_when(
      Mode_of_Travel == "auto" & Number_of_People == 1 ~ "sov",
      Mode_of_Travel == "auto" & Number_of_People == 2 ~ "hov2",
      Mode_of_Travel == "auto" & Number_of_People >= 2 ~ "hov3",
      TRUE ~ Mode_of_Travel
    )
  )

# Access mode is simply the mode used to access the prior location
access_mode <- convert_modes %>%
  arrange(hh_id, Person_Number, `Activity/Trip_Number`) %>%
  group_by(hh_id, Person_Number) %>%
  mutate(
    access_mode = lag(mode_model),
    egress_mode = lead(mode_model)
  ) %>%
  relocate(access_mode, .before = mode_model)
```


## Identify tours

```{r}
# Transit trip linking
# There are only 35 mode transfers in the survey. Not worrying about this step.
# access_mode %>% group_by(Activity_Type_Code) %>% summarize(count = n())

# link_transit_trips <- access_mode %>%
#   group_by(hh_id, Person_Number) %>%
#   filter(hh_id == 5000000081) %>% # for testing single houses
#   mutate(
#     # First correct "X" purposes where transit isn't involved.
#     # These are actually where Escort happens (e.g. hov2 becomes sov).
#     tpurp_simple = Activity_Type_Code,
#     tpurp_simple = case_when(
#       tpurp_simple != "X" ~ tpurp_simple,
#       any(c("school_bus", "bus") %in% access_mode) ~ tpurp_simple,
#       any(c("school_bus", "bus") %in% mode_model) ~ tpurp_simple,
#       any(c("school_bus", "bus") %in% egress_mode) ~ tpurp_simple,
#       TRUE ~ "Esc"
#     ),
#     transit_chain_start = ifelse(tpurp_simple == "X" & lag(tpurp_simple != "X"), 1, 0),
#     chain_id = cumsum(transit_chain_start),
#     chain_id = ifelse(tpurp_simple != "X" & lag(tpurp_simple != "X"), 0, chain_id),
#     chain_id = ifelse(is.na(chain_id), 0, chain_id)
#   ) %>%
#   group_by(hh_id, Person_Number, chain_id) %>%
#   mutate(
#     num_xfers = n(),
#     num_xfers = ifelse(chain_id == 0, 0, num_xfers - 1),
#     egress_mode = ifelse(chain_id > 0 & tpurp_simple != "X", NA, egress_mode),
#     access_mode = case_when(
#       chain_id == 0 ~ access_mode,
#       "sov" %in% access_mode ~ "pnr",
#       any(c("hov2", "hov3") %in% access_mode) ~ "knr",
#       "walk" %in% access_mode ~ "walk",
#       "bus" %in% access_mode ~ "bus",
#       TRUE ~ access_mode
#     ),
#     mode_model = case_when(
#       chain_id == 0 ~ mode_model,
#       "school_bus" %in% mode_model ~ "school_bus",
#       TRUE ~ "bus"
#     ),
#     egress_mode = case_when(
#       chain_id == 0 ~ egress_mode,
#       "sov" %in% egress_mode ~ "pnr",
#       any(c("hov2", "hov3") %in% egress_mode) ~ "knr",
#       "walk" %in% egress_mode ~ "walk",
#       "bus" %in% egress_mode ~ "bus",
#       TRUE ~ egress_mode
#     ),
#     access_mode = ifelse(mode_model == "bus", access_mode, NA),
#     egress_mode = ifelse(mode_model == "bus", egress_mode, NA)
#   ) %>%
#   filter(tpurp_simple != "X") %>%
#   mutate(
#     access_mode = case_when(
#       access_mode == "bus" ~ "walk",
#       is.na(access_mode) & mode_model == "bus" ~ "walk",
#       TRUE ~ access_mode
#     ),
#     egress_mode = case_when(
#       egress_mode == "bus" ~ "walk",
#       is.na(egress_mode) & mode_model == "bus" ~ "walk",
#       TRUE ~ egress_mode
#     )
#   ) %>%
#   select(-transit_chain_start, -chain_id, -num_xfers)


id_tours <- access_mode %>%
  arrange(hh_id, Person_Number, `Activity/Trip_Number`) %>%
  group_by(hh_id, Person_Number) %>%
  mutate(
    tour_start = case_when(
      Activity_Type_Code == "H" & `Activity/Trip_Number` == max(`Activity/Trip_Number`) ~ 0,
      Activity_Type_Code == "H" ~ 1,
      TRUE ~ 0
    ),
    tour_num = cumsum((tour_start))
  ) %>%
  # if a person only has one location listed for the day, they did not travel,
  # so assign them to "home" tour type.
  mutate(tour_type = ifelse(n() == 1, "home", NA)) %>%
  group_by(hh_id, Person_Number, tour_num) %>%
  mutate(
    tour_type = case_when(
      tour_type == "home" ~ "home",
      "W" %in% Activity_Type_Code ~ "work",
      "U" %in% Activity_Type_Code ~ "univ",
      "Sch" %in% Activity_Type_Code ~ "school",
      any(grepl("PUDO Sch", Activity_Type_Code)) ~ "PUDO_Sch",
      any(grepl("PUDO Work", Activity_Type_Code)) ~ "PUDO_Work",
      any(grepl("PUDO Other", Activity_Type_Code)) ~ "PUDO_Other",
      # "Shp" %in% Activity_Type_Code ~ "shop",
      tour_num == 0 ~ "home",
      TRUE ~ "nm"
    ),
    # complete_tour = ifelse(last(Activity_Type_Code) == "H", 1, 0),
    tour_id = paste(hh_id, Person_Number, tour_num, sep = "_")
  )

# determine tour anchor place using the max duration, but break ties by
# purpose. For any remaining ties (same purpose and duration) just make the
# first one the anchor.
mark_anchor <- id_tours %>%
  group_by(hh_id, Person_Number) %>%
  mutate(
    # activity_arr_mins = arr_hr * 60 + arr_min,
    # activity_dep_mins = dep_hr * 60 + dep_min,
    activity_arr_mins = lubridate::seconds(Arrival_Time) %>% as.integer() / 60,
    arr_hr = activity_arr_mins %/% 60,
    arr_min = activity_arr_mins %% 60,
    activity_dep_mins = lubridate::seconds(Departure_Time) %>% as.integer() / 60,
    # For people working 3rd shift, their last location is not home and does
    # not have a departure time. Give that a time of midnight for anchor calcs.
    activity_dep_mins = ifelse(
      Activity_Type_Code != "H" & `Activity/Trip_Number` == max(`Activity/Trip_Number`),
      24 * 60, activity_dep_mins
    ),
    dep_hr = activity_dep_mins %/% 60,
    dep_min = activity_dep_mins %% 60,
    activity_duration = ifelse(
      activity_arr_mins < activity_dep_mins,
      activity_dep_mins - activity_arr_mins,
      activity_dep_mins + 24 * 60 - activity_arr_mins
    ),
    activity_duration = ifelse(is.na(activity_duration), 0, activity_duration),
    temp_dur = ifelse(Activity_Type_Code == "H", 0, activity_duration)
  ) %>%
  group_by(hh_id, Person_Number, tour_num) %>%
  mutate(
    anchor = ifelse(temp_dur == max(temp_dur), 100, 0),
    anchor = case_when(
      Activity_Type_Code == "W" ~ anchor + 3,
      Activity_Type_Code == "U" ~ anchor + 2,
      Activity_Type_Code == "Sch" ~ anchor + 1,
      TRUE ~ anchor,
    ),
    anchor = ifelse(anchor == max(anchor), 1, 0),
    check = cumsum(anchor),
    anchor = ifelse(check > 1, 0, anchor),
    anchor_taz = ifelse(anchor == 1, LocationTAZ, NA),
    anchor_duration = ifelse(anchor == 1, temp_dur, NA),
    # Calculate intermediate stops
    int_stop = ifelse(
      `Activity/Trip_Number` == min(`Activity/Trip_Number`) | `Activity/Trip_Number` == max(`Activity/Trip_Number`) | anchor == 1,
      0, 1
    ),
    int_stop_fwd = ifelse(check == 0, int_stop, 0), # before anchor
    int_stop_ret = ifelse(check >= 1, int_stop, 0)  # after anchor
  ) %>%
  select(-temp_dur, -check)

# Identify primary and secondary modes. Primary is the highest-order mode on
# trip. The secondary mode is the second highest order.
id_tour_mode <- mark_anchor %>%
  mutate(
    primary_mode = case_when(
      "rail" %in% mode_model ~ "rail",
      "school_bus" %in% mode_model ~ "school_bus",
      "bus" %in% mode_model ~ "bus",
      # "hotel_shuttle" %in% mode_model ~ "hotel_shuttle",
      "tnc" %in% mode_model ~ "tnc",
      "hov3" %in% mode_model ~ "hov3",
      "hov2" %in% mode_model ~ "hov2",
      "sov" %in% mode_model ~ "sov",
      "bike" %in% mode_model ~ "bike",
      "walk" %in% mode_model ~ "walk",
      "other" %in% mode_model ~ "other",
      TRUE ~ "other"
    ),
    temp = ifelse(mode_model == primary_mode, NA, mode_model),
    secondary_mode = case_when(
      "rail" %in% temp ~ "rail",
      "school_bus" %in% temp ~ "school_bus",
      "bus" %in% temp ~ "bus",
      # "hotel_shuttle" %in% temp ~ "hotel_shuttle",
      "tnc" %in% temp ~ "tnc",
      "hov3" %in% temp ~ "hov3",
      "hov2" %in% temp ~ "hov2",
      "sov" %in% temp ~ "sov",
      "bike" %in% temp ~ "bike",
      "walk" %in% temp ~ "walk",
      "other" %in% temp ~ "other",
      TRUE ~ primary_mode
    )
  ) %>%
  select(-temp)

tour_file <- id_tour_mode %>%
  group_by(tour_id) %>%
  summarize(
    hh_id = first(hh_id),
    Person_Number = first(Person_Number),
    tour_num = first(tour_num),
    tour_type = first(tour_type),
    # complete_tour = first(complete_tour),
    num_trips = n(),
    anchor_taz = max(anchor_taz, na.rm = TRUE),
    anchor_start_hr = sum(arr_hr[anchor == 1]),
    # anchor_end_hr = sum(dep_hr[anchor == 1]),
    anchor_duration = max(anchor_duration, na.rm = TRUE),
    int_stop_fwd = sum(int_stop_fwd),
    int_stop_ret = sum(int_stop_ret),
    primary_mode = first(primary_mode),
    secondary_mode = first(secondary_mode),
    access_mode = first(na.omit(access_mode)),
    egress_mode = last(na.omit(egress_mode)),
    HH_Members_Max = max(HH_Members, na.rm = TRUE),
    HH_Members_Min = min(HH_Members, na.rm = TRUE)
  ) %>%
  mutate(anchor_taz = ifelse(anchor_taz == -Inf, NA, anchor_taz)) %>%
  # tours with tour_num = 0 are where the person starts the day not at home.
  filter(tour_num > 0 | tour_type == "home")
```

```{r}
stops_file <- id_tour_mode %>%
  ungroup() %>%
  filter(int_stop == 1) %>%
  mutate(stop_taz = LocationTAZ) %>%
  select(
    tour_id, int_stop_fwd, int_stop_ret, stop_taz, Activity_Type_Code,
    duration = activity_duration
  ) %>%
  # determine primary forward and return stop based on duration
  group_by(tour_id) %>%
  mutate(stop_id = row_number()) %>%
  ungroup() %>%
  arrange(tour_id, int_stop_fwd, desc(duration)) %>%
  group_by(tour_id, int_stop_fwd) %>%
  mutate(primary_stop = ifelse(row_number() == 1, 1, 0)) %>%
  ungroup() %>%
  arrange(tour_id, stop_id) %>%
  relocate(stop_id, .after = tour_id)
```


```{r}
# Update household file with numbers of workers who took a work tour that day
tours_by_hh <- tour_file %>%
  group_by(hh_id, Person_Number, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = c(hh_id, Person_Number), names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  mutate(WorkersThatDay = ifelse(work > 0, 1, 0)) %>%
  group_by(hh_id) %>%
  summarize(across(nm:WorkersThatDay, ~ sum(.x))) %>%
  rename_with(~ paste0(.x, "_tours"), nm:PUDO_Other)
  

hh_add_tours <- hh_add_strct %>%
  left_join(tours_by_hh, by = "hh_id") %>%
  relocate(WorkersThatDay, .after = WAdults) %>%
  mutate(
    BasicPattern = paste0(
      "P_",
      WorkersThatDay,
      Number_Persons - HHKids - WorkersThatDay, # adults not working that day,
      HHKids
    )
  )
```


## Create Trip File

```{r}
trip_file <- mark_anchor %>%
  group_by(hh_id, Person_Number) %>%
  mutate(
    trip_dep_hr = dep_hr,
    trip_dep_min = dep_min,
    trip_arr_hr = lead(arr_hr),
    trip_arr_min = lead(arr_min),
    trip_mode = lead(mode_model),
    # trip_orig_ptype = ptype,
    # trip_dest_ptype = lead(ptype),
    # trip_dest_ptype = ifelse(
    #   is.na(trip_dest_ptype) & trip_orig_ptype != "Home", "Home", trip_dest_ptype
    # ),
    trip_orig_purp = Activity_Type_Code,
    trip_dest_purp = lead(Activity_Type_Code),
    trip_o_taz = LocationTAZ,
    trip_d_taz = lead(LocationTAZ),
    trip_pa_format = ifelse(trip_dest_purp == "H", 0, 1),
    trip_p_taz = ifelse(trip_pa_format == 1, trip_o_taz, trip_d_taz),
    trip_a_taz = ifelse(trip_pa_format == 1, trip_d_taz, trip_o_taz),
    trip_p_purp = ifelse(trip_pa_format == 1, trip_orig_purp, trip_dest_purp),
    trip_a_purp = ifelse(trip_pa_format == 1, trip_dest_purp, trip_orig_purp),
    trip_purpose = case_when(
      trip_p_purp == "H" ~ paste0("HB", trip_a_purp),
      trip_p_purp == "W" | trip_a_purp == "W" ~ "NHBW",
      trip_p_purp == "Shp" | trip_a_purp == "Shp" ~ "NHBShp",
      TRUE ~ "NHBO"
    )
  ) %>%
  select(-LocationTAZ, -Activity_Type_Code, -mode_model) %>%
  # Remove the last place for each person. This also removes people who didn't
  # travel and so only have one place listed.
  filter(`Activity/Trip_Number` != max(`Activity/Trip_Number`)) %>%
  # ID external trips
  mutate(ix_type = case_when(
    is.na(trip_o_taz) & is.na(trip_d_taz) ~ "EE",
    !is.na(trip_o_taz) & !is.na(trip_d_taz) ~ "II",
    TRUE ~ "IX"
  ))
```

## Add tour summary to person file

```{r}
tours_by_per <- tour_file %>%
  group_by(hh_id, Person_Number, tour_type) %>%
  summarize(count = n()) %>%
  pivot_wider(
    id_cols = hh_id:Person_Number, names_from = tour_type, 
    values_from = count, values_fill = 0
  ) %>%
  rename_with(~ paste0(.x, "_tours"), nm:PUDO_Other)

per_add_tour_counts <- per_calc_ptypes %>%
  left_join(
    hh_with_tazs %>% select(-WEIGHT_FCTR), by = "hh_id"
  ) %>%
  left_join(tours_by_per, by = c("hh_id", "Person_Number")) %>%
  mutate(
    home_tours = ifelse(is.na(home_tours), 1, 0),
    nm_tours = ifelse(is.na(nm_tours), 0, nm_tours),
    work_tours = ifelse(is.na(work_tours), 0, work_tours),
    school_tours = ifelse(is.na(school_tours), 0, school_tours),
    univ_tours = ifelse(is.na(univ_tours), 0, univ_tours)
  )
```

```{r}
# check to see how many people by work status are making 0 work tours
# per_add_tour_counts %>%
#   group_by(wkstat, wplace) %>%
#   summarize(total_persons = n()) %>%
#   left_join(
#     per_add_tour_counts %>%
#       filter(work_tours == 0) %>%
#       group_by(wkstat, wplace) %>%
#       summarize(per_with_0work = n()),
#     by = c("wkstat", "wplace")
#   ) %>%
#   View()
```

```{r}
per_calc_iz <- per_add_tour_counts %>%
  mutate(
    IZ_Work = ifelse(HomeTAZ == WorkTAZ, 1, 0),
    IZ_School = ifelse(HomeTAZ == SchoolTAZ, 1, 0)
  )
```

```{r}
tour_remove_home <- tour_file %>%
  filter(tour_type != "home" & !is.na(anchor_start_hr))
```

## EDA for Non-Mandatory

```{r}
# Add data needed for EDA like skim length and TOD
trip_add_tod <- trip_file %>%
  mutate(tod = case_when(
    arr_hr >= 6 & arr_hr < 9 ~ "AM",
    arr_hr >= 9 & arr_hr < 15 ~ "MD",
    arr_hr >= 15 & arr_hr < 18 ~ "PM",
    TRUE ~ "NT",
  ))

skim <- read_csv("data/input/skims/ff_skim.csv")
trip_add_skim <- trip_add_tod %>%
  left_join(skim, by = c("trip_p_taz" = "InternalTAZ", "trip_a_taz" = "InternalTAZ:1")) %>%
  rename(skim_time = Time, skim_length = Distance)

# The EDA is going to regress on attraction end employment
sedata <- read_csv("data/input/sedata/NewDemographics.csv")
temp <- trip_add_skim %>%
  left_join(sedata, by = c("trip_a_taz" = "TAZ")) %>%
  filter(trip_purpose %in% c(
    "HBO",
    "HBSR",
    "HBShp",
    "NHBO",
    "NHBShp",
    "HBEO",
    "HBG"
  )) %>%
  mutate(
    tour_type = "all",
    homebased = "all",
    purp_scheme = trip_purpose,
    # dur_scheme = case_when(
    #   trip_purpose != "HBO" ~ "all",
    #   activity_duration < 30 ~ "short",
    #   TRUE ~ "long"
    # )
    dur_scheme = "all"
  )
temp_per <- per_calc_iz %>%
  mutate(
    is_worker = ifelse(Employment == "Yes", 1, 0),
    is_senior = Senior,
    is_kid = Kid
  )

eda_df <- trip_eda(trip_df = temp)
eda_df <- eda_df %>%
  select(-tour_type, -homebased)
```

```{r}
per_fix_na <- per_calc_iz %>%
  mutate(WEIGHT_FCTR = ifelse(WEIGHT_FCTR == "NA", NA, WEIGHT_FCTR))
```



```{r}
write_csv(per_fix_na, "data/_private/hh_survey_2023/output/output_persons.csv", na = "")
write_csv(hh_add_tours, "data/_private/hh_survey_2023/output/output_households.csv", na = "")

write_csv(tour_remove_home, "data/_private/hh_survey_2023/output/output_tours.csv", na = "")
write_csv(stops_file, "data/_private/hh_survey_2023/output/output_stops.csv", na = "")
write_csv(trip_add_skim, "data/_private/hh_survey_2023/output/output_trips.csv", na = "")
write_csv(eda_df, "data/_private/hh_survey_2023/output/eda.csv", na = "")
```

